CREATE TABLE [dbo].[Author]
(
	[Id] UNIQUEIDENTIFIER NOT NULL CONSTRAINT [PK_Author] PRIMARY KEY,
	[BookId] UNIQUEIDENTIFIER NOT NULL,
	[FirstName] NVARCHAR(50) NOT NULL,
	[LastName] NVARCHAR(50) NOT NULL,
	CONSTRAINT [FK_Author_Book] FOREIGN KEY (BookId) REFERENCES [dbo].[Book] ([Id])
)
